### PR TITLE
qaz

### PR DESCRIPTION
**Pull request by mustdo-afk**

### CODE REVIEW

**Comment by mustdo-afk** [comment]
begin benchmark

**Comment by lutengda** [comment]
begin benchmark

**Comment by lutengda** [comment]
Me too

**Comment by lutengda** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_f5da432.html

**Comment by lutengda** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_f5da432.html

**Comment by lutengda** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_f5da432.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_f5da432.html

**Comment by lutengda** [comment]
begin benchmark

**Comment by lutengda** [comment]
begin benchmark

**Comment by lutengda** [comment]
begin benchmark

**Pull request closed without merging**
